version: '2'
services:
  mock:
    image: docops-template-api
    build: .
    ports:
     - "${PRISM_PORT}:8010"
    volumes:
     - ./:/model/
     - /model/node_modules
    command: sh -c "node_modules/gulp/bin/gulp.js validate && prism run -c prism.json -s ./output/swagger.json -p 8010 --cors --list"
  swagger:
    image: docops-template-api
    build: .
    ports:
     - "${SWAGGER_PORT}:3000"
    volumes:
     - ./:/model/
     - /model/node_modules
    entrypoint: ['yarn', 'run']
    command: ['compile-start']
