version: '2'
services:
  mock:
    image: docops-mock
    build: .
    ports:
     - "${PRISM_PORT}:8010"
    volumes:
     - ./:/model/
     - /model/node_modules
    command: sh -c "node compile.js && prism run -c prism.json -s ./output/swagger.json -p 8010 --cors --list"
  swagger:
    image: docops-swagger
    build: .
    ports:
     - "${SWAGGER_PORT}:3000"
    volumes:
     - ./:/model/
     - /model/node_modules
    command: sh -c "node compile.js && npm start"
